Feat/validate input generator 272
eoscostarica/eosio-components pull request #86
Opened 2022-08-16 19:48 UTC by xavier506

2022-08-17 14:01 UTC, AngeloCG97 requested changes

2022-08-22 17:23 UTC, AngeloCG97 reviewed
Please review CodeFactor alerts.

2022-08-24 13:42 UTC, AngeloCG97 requested changes

2022-08-24 13:42 UTC, AngeloCG97 commented on src/lib/ArrayTextField/index.js
> +
Unnecessary space

2022-08-25 02:42 UTC, tetogomez requested changes
See the comments

2022-08-25 02:42 UTC, tetogomez commented on src/lib/BPJsonGenerator/EndpointsForm.js
> +
delete this blank space

2022-08-25 02:42 UTC, tetogomez commented on src/lib/BPJsonGenerator/EndpointsForm.js
> +
delete this blank space

2022-08-25 02:42 UTC, tetogomez commented on src/lib/BPJsonGenerator/EndpointsForm.js
> +
delete this blank space

2022-08-25 02:42 UTC, tetogomez commented on src/lib/BPJsonGenerator/FeaturesForm.js
> +
delete this blank space

2022-08-25 02:42 UTC, tetogomez commented on src/lib/utils/schemas.js
> +
delete this blank space

2022-08-25 02:42 UTC, tetogomez commented on src/lib/utils/schemas.js
> +
delete this blank space

2022-08-25 02:42 UTC, tetogomez commented on src/lib/utils/schemas.js
> +
delete this blank space

2022-08-25 21:20 UTC, AngeloCG97 approved these changes
LGTM

2022-08-25 21:29 UTC, leisterfrancisco requested changes

2022-08-25 21:29 UTC, leisterfrancisco commented on src/lib/BPJsonGenerator/BoxDropzone.js
> +
remove empty line

2022-08-25 21:29 UTC, leisterfrancisco commented on src/lib/BPJsonGenerator/BoxDropzone.js
> +          }
Recommendation

```
setErrorMessage(error instanceof SyntaxError ? "The file does not have the correct JSON format" : error.message)
```

2022-08-26 15:16 UTC, fvives99 approved these changes
LGTM

2022-08-26 18:14 UTC, tetogomez requested changes

2022-08-26 18:14 UTC, tetogomez commented on src/lib/ArrayTextField/index.js
> -
This blank space is necessary.
clean code rule 

`order import by a group`

first group: third-party libraries
second group: project libraries (components, config, utils, etc)
third group: files on the same level (styles files or a specific component used only here)

so, these groups should be separated by a blank space

2022-08-26 18:14 UTC, tetogomez commented on src/lib/ArrayTextField/index.js
> +
delete blank space

2022-08-26 18:14 UTC, tetogomez commented on src/lib/BPJsonGenerator/EndpointsForm.js
> +import Styles from './styles'
same here, please check the comment about `order import by a group`

2022-08-26 18:14 UTC, tetogomez commented on src/lib/BPJsonGenerator/EndpointsForm.js
> +  }
after if declaration always add blank space

2022-08-26 18:14 UTC, tetogomez commented on src/lib/BPJsonGenerator/FeaturesForm.js
> +import { NODE_EXTRA_KEYS } from '../utils'
`order import by a group`

2022-09-01 02:00 UTC, tetogomez approved these changes
LGTM

good job!

2022-09-01 02:01 UTC, merged